---
# tasks file for erlang

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- debug: msg="Ansible distribution {{ ansible_distribution }}"

- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- include: Amazon.yml
  when: ansible_distribution == "Amazon"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: common.yml